trigger:
  branches:
    include:
      - main

pool:
  name: Default

variables:
  DATABRICKS_HOST: $(DATABRICKS_HOST_DEV)
  DATABRICKS_TOKEN: $(DATABRICKS_TOKEN_DEV)

steps:

  - script: |
      cd files
      pip install databricks-cli
      databricks bundle validate
      databricks bundle deploy --target=dev
    env:
      DATABRICKS_HOST: $(DATABRICKS_HOST)
      DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)
